version: '3.8'

services:
  tarantool:
    container_name: tarantool
    image: tarantool/tarantool
    ports:
      - 3301:3301
    volumes:
      # - tarantool-data:/var/lib/tarantool
      - ./tarantool:/opt/tarantool
    command: ["tarantool", "/opt/tarantool/init.lua"]

volumes:
  tarantool-data: