version: '3.8'

services:
  tarantool:
    container_name: tarantool
    image: tarantool/tarantool
    ports:
      - 3301:3301
    volumes:
      # - tarantool-data:/var/lib/tarantool
      - ./tarantool:/opt/tarantool
    command: ["tarantool", "/opt/tarantool/init.lua"]

  # api:
  # build: 
  #    context: .
  #    dockerfile: Dockerfile.api
  #  ports:
  #    - 8080:8080
  #  restart: always
  #  depends_on:
  #    - tarantool

  # proxy:
  # build: 
  #  context: .
  #  dockerfile: Dockerfile.proxy
  #  ports:
  #    - 8000:8000
  #  restart: always
  #  depends_on:
  #    - tarantool

volumes:
  tarantool-data: